### ISSUE TITLE
Support Multiple types on output

### ISSUE THREAD

**Issue by raditya1710** [tcframe/tcframe#123]
I can't generate multiple types in outputFormat, e.g. String and Integer.

**Comment by fushar** [comment]
One possible idea is to have multiple methods, e.g.

- `OutputFormat1()`
- `OutputFormat2()`

etc, and an output is valid if it satisfies at least one format.

Will look into it later.

**Comment by jonathanirvings** [comment]
@raditya1710 anyway, the current "hack" is to remove `OutputFormat()` completely. If you do so, the output format will not be checked.
