### ISSUE TITLE
Support hidden/config variable assignment in sample case definitions

### ISSUE THREAD

**Issue by fushar** [tcframe/tcframe#38]
Suppose the input format is a list of strings, of undefined length. We can use this Problem spec:

```
class Problem : public BaseProblem {
protected:
    int L;
    vector<string> S;    

    void InputFormat() {
        LINES(S) % SIZE(L);
    }
};
```

Then, in the test case definitions, we can use:

```
CASE(L = 3, S = { "abc", "def", ghi" });
```

However, there is currently no way to set L in sample case definition.

**Comment by fushar** [comment]
Will be solved by #98.

**Comment by raditya1710** [comment]
Still have a bug in function `OutputFormat`

`LINES(result) % SIZE(N_result)` with **defined length** (computed in function **OutputFormat()** still give me output like this:

```
Reasons:
    * Cannot parse for 'result[2]'. Found: <EOF>
```

And this is part of my code that still buggy:
```
void OutputFormat() {
	int N_result = 0;
	for(int i = 0;i < (int)op.size(); ++i){
		if(op[i] == 2){
			N_result++;
		}
	}
	LINES(res) % SIZE(N_result);
}
```

**Comment by fushar** [comment]
OK, I think the best way to handle this is to apply the lifecycle methods `BeforeTestCase()` and `AfterTestCase()` for sample test cases as well. This way, you can calculate the correct value of `N_result` in `AfterTestCase()`.

**Comment by fushar** [comment]
Ugh, nevermind. The above is totally wrong because `AfterTestCase()` can possibly overwrite the input variables that have been parsed from the sample input literals.

How about adding a new hook, like, `BeforeOutputFormat()`? Since I think this is the only use case.

**Comment by jonathanirvings** [comment]
I have another alternative in my mind.

So by using `BeforeOutputFormat()`, after testcase has been defined, it will go to `AfterTestCase()` and `BeforeOutputFormat()`? Seems a bit confusing to me.

What about `BeforeSampleTestCase()` and `AfterSampleTestCase()` instead?

**Comment by jonathanirvings** [comment]
PS : By doing the above, if the user wants to make `AfterSampleTestCase()` and `AfterTestCase()` the same, they can just do AfterSampleTestCase() { AfterTestCase(); }` to avoid code duplication. And they can make them different as well.

**Comment by jonathanirvings** [comment]
After another thought, @fushar's idea is not really confusing since the method names are quite intuitive. So we can go with @fushar's idea then.
