### ISSUE TITLE
Cannot generate a lot of test-cases

### ISSUE THREAD

**Issue by afaji** [tcframe/tcframe#54]
when generating a huge number of test cases, you'll get Exit Code: 1 with a message of "Too many open files"

**Comment by jonathanirvings** [comment]
@afaji321 Can change the limit of "opened files" using "ulimit -n"?
E.g. "ulimit -n 1024" and then re-run the runner

**Comment by fushar** [comment]
I think this is somehow fixed during 1.0 refactor. I was able to generate 2048 test cases.

Please reopen if you think this is still happening.
